# Generated by Django 5.1.7 on 2025-03-20 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="image"
            ),
        ),
    ]
