repos:
  # 1️⃣ Auto-format code using Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  # 2️⃣ Sort imports using isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # 3️⃣ Basic linting using Flake8 (Allows only critical warnings)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503"]  # Ignore line-length and minor issues

  # 4️⃣ Lint JSON and JavaScript using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        types: [json, javascript, css, html, markdown]

  # 5️⃣ Trim trailing whitespace in all text files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer  # Ensure files end with a newline
